@startuml

class カート
class 商品
class 価格
class 合計金額
class 会計
class 消費税率
class 会計金額
class ポイント計算
class ポイント
class キャンペーン

商品 "1...*" -- "1" 価格
カート "0...*" - "0...*" 商品
カート "1...*" -- "1" 合計金額
カート "1" -- "1" 会計
会計 "0...*" -- "1" 消費税率
会計 "1" -- "1" 会計金額
ポイント計算 "1" -- "1" 算出ロジック
ポイント計算 "1" -- "1" 会計金額 : 入力 >
ポイント計算 "1" - "1" ポイント : 出力 >
ポイント計算 "1" -- "1" キャンペーン
キャンペーン "1" -- "1" キャンペーン : 階層

@enduml