@startuml

商品 "0..*" -- "1" 価格
商品 "0..*" -- "1" 種別
カート "0..*" - "0..*" 商品
カート "1" --- "1" 基本ポイント算出ロジック
カート "1..*" - "1" 合計金額
カート "1..*" -- "1" ポイント
カート "1" -- "1" キャンペーン
キャンペーン "1" -- "1" キャンペーン : 階層
基本ポイント算出ロジック "1..*" -l "1" 合計金額

@enduml